plugins {
    id 'net.fabricmc.fabric-loom'
}
version = rootProject.mod_version
group = rootProject.maven_group
base {
    archivesName = "map6b6t-26.x+"
}
dependencies {
    minecraft "com.mojang:minecraft:26.1.2"
    modImplementation "net.fabricmc:fabric-loader:0.19.5"
    modImplementation fabricApi.module("fabric-command-api-v2", "0.147.0+26.1.2")
    modImplementation fabricApi.module("fabric-lifecycle-events-v1", "0.147.0+26.1.2")
    modImplementation fabricApi.module("fabric-rendering-v1", "0.147.0+26.1.2")
}
sourceSets {
    main {
        java.srcDirs = ['src/main/java']
    }
}
